// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL0uch6fZ_eMhFc-AZG89ez_tJY7v8AtQ',
    appId: '1:239318938066:web:bf2ca880b8b1f46a27980b',
    messagingSenderId: '239318938066',
    projectId: 'myunifyp-d70f5',
    authDomain: 'myunifyp-d70f5.firebaseapp.com',
    storageBucket: 'myunifyp-d70f5.appspot.com',
    measurementId: 'G-WK0HJMS8XC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn4r-ghDi_A5ouPLKx8-l1czC0HRIZPKc',
    appId: '1:239318938066:android:29c3a1979c51a0a627980b',
    messagingSenderId: '239318938066',
    projectId: 'myunifyp-d70f5',
    storageBucket: 'myunifyp-d70f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4jBkVUs6cGvfvb4QltJk6Gma9g_AJ5M0',
    appId: '1:239318938066:ios:b60d1f9cc754277227980b',
    messagingSenderId: '239318938066',
    projectId: 'myunifyp-d70f5',
    storageBucket: 'myunifyp-d70f5.appspot.com',
    iosBundleId: 'com.example.wheatDiseaseDetection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCL0uch6fZ_eMhFc-AZG89ez_tJY7v8AtQ',
    appId: '1:239318938066:web:df30d9e9509c89da27980b',
    messagingSenderId: '239318938066',
    projectId: 'myunifyp-d70f5',
    authDomain: 'myunifyp-d70f5.firebaseapp.com',
    storageBucket: 'myunifyp-d70f5.appspot.com',
    measurementId: 'G-3JQLRJR4NN',
  );
}
